[project]
name = "study-tracker-backend"
version = "0.0.0"
description = "Backend API for tracking study time for DevOps certifications"
readme = "README.md"
authors = [{ name = "Buchta Tomas", email = "test@gmail.com" }]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "ruff>=0.16.2",
    "uvicorn>=0.52.1",
]

[project.scripts]
study-tracker-api = "backend.main:main"

[tool.hatch.build.targets.wheel]
packages = ["src/backend"]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
